### ISSUE TITLE
Failure calling the macro

### ISSUE THREAD

**Issue by cvgaviao** [drhooves/SelectionTools#2]
Sometimes after select shortcut S+E, I'm getting this error with version 0.17:

> Traceback (most recent call last):
  File "/home/cvg/.FreeCAD/Mod/SelectionTools/ListSelect.py", line 33, in select
    saveUserSettings()
  File "/home/cvg/.FreeCAD/Mod/SelectionTools/ListSelect.py", line 190, in saveUserSettings
    prevTrans = obj.ViewObject.Transparency
AttributeError: 'NoneType' object has no attribute 'ViewObject'

**Comment by cvgaviao** [comment]
seems that this error occurs when calling the macro when the cursor is not hovering any object

**Comment by ceeli** [comment]
Hi, thanks for reporting. I'm going to look into it on the weekend
Edit: Oh... wrong account, but same person ;)

**Comment by dietmarczekay** [comment]
please put a version online with "pyside2-rcc -o SelectionTools_rc.py Resources/SelectionTools.qrc"
Then I can load the plugin in FC_0.19
